import {
  defineObject,
  FieldType,
  getFieldUniversalIdentifier,
  getSystemRelationFieldUniversalIdentifier,
  OnDeleteAction,
  RelationType,
} from 'twenty-sdk/define';

import {
  APPLICATION_UNIVERSAL_IDENTIFIER,
  CLIENT_PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
  COMPANY_OBJECT_UNIVERSAL_IDENTIFIER,
  OPPORTUNITY_OBJECT_UNIVERSAL_IDENTIFIER,
  OPERATIONAL_FINDING_OBJECT_UNIVERSAL_IDENTIFIER,
  PROJECT_DECISION_OBJECT_UNIVERSAL_IDENTIFIER,
  TASK_OBJECT_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

const f = (name: string) =>
  getFieldUniversalIdentifier({
    applicationUniversalIdentifier: APPLICATION_UNIVERSAL_IDENTIFIER,
    objectUniversalIdentifier: CLIENT_PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
    name,
  });

export default defineObject({
  universalIdentifier: CLIENT_PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'clientProject',
  namePlural: 'clientProjects',
  labelSingular: 'Client Project',
  labelPlural: 'Client Projects',
  description: 'A paid engagement with a local business client, tracked from kickoff to completion.',
  icon: 'IconBriefcase',
  isSearchable: true,
  isUICreatable: true,
  isUIEditable: true,
  fields: [
    {
      universalIdentifier: f('name'),
      type: FieldType.TEXT,
      name: 'name',
      label: 'Project Name',
      isNullable: true,
    },
    {
      universalIdentifier: f('company'),
      type: FieldType.RELATION,
      name: 'company',
      label: 'Company',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: getSystemRelationFieldUniversalIdentifier({
        applicationUniversalIdentifier: APPLICATION_UNIVERSAL_IDENTIFIER,
        objectUniversalIdentifier: COMPANY_OBJECT_UNIVERSAL_IDENTIFIER,
        relationTargetObjectUniversalIdentifier: CLIENT_PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
      }),
      relationTargetObjectMetadataUniversalIdentifier: COMPANY_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'companyId',
      },
    },
    {
      universalIdentifier: f('opportunity'),
      type: FieldType.RELATION,
      name: 'opportunity',
      label: 'Opportunity',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: getSystemRelationFieldUniversalIdentifier({
        applicationUniversalIdentifier: APPLICATION_UNIVERSAL_IDENTIFIER,
        objectUniversalIdentifier: OPPORTUNITY_OBJECT_UNIVERSAL_IDENTIFIER,
        relationTargetObjectUniversalIdentifier: CLIENT_PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
      }),
      relationTargetObjectMetadataUniversalIdentifier: OPPORTUNITY_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'opportunityId',
      },
    },
    {
      universalIdentifier: f('projectValue'),
      type: FieldType.CURRENCY,
      name: 'projectValue',
      label: 'Project Value',
      isNullable: true,
    },
    {
      universalIdentifier: f('priority'),
      type: FieldType.SELECT,
      name: 'priority',
      label: 'Priority',
      defaultValue: "'MEDIUM'",
      options: [
        { position: 0, label: 'Low', value: 'LOW', color: 'gray' },
        { position: 1, label: 'Medium', value: 'MEDIUM', color: 'blue' },
        { position: 2, label: 'High', value: 'HIGH', color: 'orange' },
        { position: 3, label: 'Urgent', value: 'URGENT', color: 'red' },
      ],
    },
    {
      universalIdentifier: f('status'),
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      defaultValue: "'PLANNED'",
      options: [
        { position: 0, label: 'Planned', value: 'PLANNED', color: 'blue' },
        { position: 1, label: 'Active', value: 'ACTIVE', color: 'green' },
        { position: 2, label: 'Waiting on Me', value: 'WAITING_ON_ME', color: 'orange' },
        { position: 3, label: 'Waiting on Client', value: 'WAITING_ON_CLIENT', color: 'yellow' },
        { position: 4, label: 'Blocked', value: 'BLOCKED', color: 'red' },
        { position: 5, label: 'Review', value: 'REVIEW', color: 'purple' },
        { position: 6, label: 'Delivered', value: 'DELIVERED', color: 'sky' },
        { position: 7, label: 'Completed', value: 'COMPLETED', color: 'jade' },
        { position: 8, label: 'Cancelled', value: 'CANCELLED', color: 'gray' },
      ],
    },
    {
      universalIdentifier: f('currentPhase'),
      type: FieldType.TEXT,
      name: 'currentPhase',
      label: 'Current Phase',
      isNullable: true,
    },
    {
      universalIdentifier: f('nextPhase'),
      type: FieldType.TEXT,
      name: 'nextPhase',
      label: 'Next Phase',
      isNullable: true,
    },
    {
      universalIdentifier: f('startedAt'),
      type: FieldType.DATE,
      name: 'startedAt',
      label: 'Started',
      isNullable: true,
    },
    {
      universalIdentifier: f('targetCompletionDate'),
      type: FieldType.DATE,
      name: 'targetCompletionDate',
      label: 'Target Completion',
      isNullable: true,
    },
    {
      universalIdentifier: f('paymentStructure'),
      type: FieldType.TEXT,
      name: 'paymentStructure',
      label: 'Payment Structure',
      description: 'e.g. 50% deposit, 25% at milestone, 25% on delivery',
      isNullable: true,
    },
    {
      universalIdentifier: f('amountPaid'),
      type: FieldType.CURRENCY,
      name: 'amountPaid',
      label: 'Amount Paid',
      isNullable: true,
    },
    {
      universalIdentifier: f('paymentStatus'),
      type: FieldType.SELECT,
      name: 'paymentStatus',
      label: 'Payment Status',
      defaultValue: "'NOT_INVOICED'",
      options: [
        { position: 0, label: 'Not Invoiced', value: 'NOT_INVOICED', color: 'gray' },
        { position: 1, label: 'Deposit Due', value: 'DEPOSIT_DUE', color: 'blue' },
        { position: 2, label: 'Partially Paid', value: 'PARTIALLY_PAID', color: 'amber' },
        { position: 3, label: 'Paid', value: 'PAID', color: 'green' },
        { position: 4, label: 'Overdue', value: 'OVERDUE', color: 'red' },
      ],
    },
    {
      universalIdentifier: f('paymentMethod'),
      type: FieldType.TEXT,
      name: 'paymentMethod',
      label: 'Payment Method',
      isNullable: true,
    },
    {
      universalIdentifier: f('paidDate'),
      type: FieldType.DATE,
      name: 'paidDate',
      label: 'Paid On',
      isNullable: true,
    },
    {
      universalIdentifier: f('nextPaymentDue'),
      type: FieldType.DATE,
      name: 'nextPaymentDue',
      label: 'Next Payment Due',
      isNullable: true,
    },
    {
      universalIdentifier: f('repository'),
      type: FieldType.LINKS,
      name: 'repository',
      label: 'Repository',
      isNullable: true,
    },
    {
      universalIdentifier: f('productionSite'),
      type: FieldType.LINKS,
      name: 'productionSite',
      label: 'Production Site',
      isNullable: true,
    },
    {
      universalIdentifier: f('primarySystem'),
      type: FieldType.TEXT,
      name: 'primarySystem',
      label: 'Primary System',
      description: 'The main system running their business (e.g. Toast, Square, QuickBooks)',
      isNullable: true,
    },
    {
      universalIdentifier: f('nextAction'),
      type: FieldType.TEXT,
      name: 'nextAction',
      label: 'Next Action',
      isNullable: true,
    },
    {
      universalIdentifier: f('blockedReason'),
      type: FieldType.TEXT,
      name: 'blockedReason',
      label: 'Blocked Reason',
      isNullable: true,
    },
    {
      universalIdentifier: f('waitingOn'),
      type: FieldType.TEXT,
      name: 'waitingOn',
      label: 'Waiting On',
      isNullable: true,
    },
    {
      universalIdentifier: f('summary'),
      type: FieldType.RICH_TEXT,
      name: 'summary',
      label: 'Summary',
      isNullable: true,
    },
    {
      universalIdentifier: f('tasks'),
      type: FieldType.RELATION,
      name: 'tasks',
      label: 'Tasks',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: getSystemRelationFieldUniversalIdentifier({
        applicationUniversalIdentifier: APPLICATION_UNIVERSAL_IDENTIFIER,
        objectUniversalIdentifier: TASK_OBJECT_UNIVERSAL_IDENTIFIER,
        relationTargetObjectUniversalIdentifier: CLIENT_PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
      }),
      relationTargetObjectMetadataUniversalIdentifier: TASK_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    {
      universalIdentifier: f('operationalFindings'),
      type: FieldType.RELATION,
      name: 'operationalFindings',
      label: 'Findings',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: getFieldUniversalIdentifier({
        applicationUniversalIdentifier: APPLICATION_UNIVERSAL_IDENTIFIER,
        objectUniversalIdentifier: OPERATIONAL_FINDING_OBJECT_UNIVERSAL_IDENTIFIER,
        name: 'clientProject',
      }),
      relationTargetObjectMetadataUniversalIdentifier: OPERATIONAL_FINDING_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    {
      universalIdentifier: f('decisions'),
      type: FieldType.RELATION,
      name: 'decisions',
      label: 'Decisions',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: getFieldUniversalIdentifier({
        applicationUniversalIdentifier: APPLICATION_UNIVERSAL_IDENTIFIER,
        objectUniversalIdentifier: PROJECT_DECISION_OBJECT_UNIVERSAL_IDENTIFIER,
        name: 'clientProject',
      }),
      relationTargetObjectMetadataUniversalIdentifier: PROJECT_DECISION_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
  ],
});