import {
  defineObject,
  FieldType,
  getFieldUniversalIdentifier,
  getSystemRelationFieldUniversalIdentifier,
  OnDeleteAction,
  RelationType,
} from 'twenty-sdk/define';

import {
  APPLICATION_UNIVERSAL_IDENTIFIER,
  CLIENT_PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
  COMPANY_OBJECT_UNIVERSAL_IDENTIFIER,
  OPERATIONAL_FINDING_OBJECT_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

const f = (name: string) =>
  getFieldUniversalIdentifier({
    applicationUniversalIdentifier: APPLICATION_UNIVERSAL_IDENTIFIER,
    objectUniversalIdentifier: OPERATIONAL_FINDING_OBJECT_UNIVERSAL_IDENTIFIER,
    name,
  });

export default defineObject({
  universalIdentifier: OPERATIONAL_FINDING_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'operationalFinding',
  namePlural: 'operationalFindings',
  labelSingular: 'Operational Finding',
  labelPlural: 'Operational Findings',
  description: 'A problem or automation opportunity observed in a client business (Audit to Optimize to Automate).',
  icon: 'IconBulb',
  isSearchable: true,
  isUICreatable: true,
  isUIEditable: true,
  fields: [
    {
      universalIdentifier: f('name'),
      type: FieldType.TEXT,
      name: 'name',
      label: 'Finding',
      isNullable: true,
    },
    {
      universalIdentifier: f('company'),
      type: FieldType.RELATION,
      name: 'company',
      label: 'Company',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: getSystemRelationFieldUniversalIdentifier({
        applicationUniversalIdentifier: APPLICATION_UNIVERSAL_IDENTIFIER,
        objectUniversalIdentifier: COMPANY_OBJECT_UNIVERSAL_IDENTIFIER,
        relationTargetObjectUniversalIdentifier: OPERATIONAL_FINDING_OBJECT_UNIVERSAL_IDENTIFIER,
      }),
      relationTargetObjectMetadataUniversalIdentifier: COMPANY_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'companyId',
      },
    },
    {
      universalIdentifier: f('clientProject'),
      type: FieldType.RELATION,
      name: 'clientProject',
      label: 'Client Project',
      isNullable: true,
      relationTargetFieldMetadataUniversalIdentifier: getFieldUniversalIdentifier({
        applicationUniversalIdentifier: APPLICATION_UNIVERSAL_IDENTIFIER,
        objectUniversalIdentifier: CLIENT_PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
        name: 'operationalFindings',
      }),
      relationTargetObjectMetadataUniversalIdentifier: CLIENT_PROJECT_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'clientProjectId',
      },
    },
    {
      universalIdentifier: f('area'),
      type: FieldType.SELECT,
      name: 'area',
      label: 'Area',
      defaultValue: "'OPERATIONS'",
      options: [
        { position: 0, label: 'Sales', value: 'SALES', color: 'violet' },
        { position: 1, label: 'Operations', value: 'OPERATIONS', color: 'blue' },
        { position: 2, label: 'Marketing', value: 'MARKETING', color: 'pink' },
        { position: 3, label: 'Customer Experience', value: 'CUSTOMER_EXPERIENCE', color: 'orange' },
        { position: 4, label: 'Payments', value: 'PAYMENTS', color: 'green' },
        { position: 5, label: 'Scheduling', value: 'SCHEDULING', color: 'cyan' },
        { position: 6, label: 'Menu & Pricing', value: 'MENU_PRICING', color: 'yellow' },
        { position: 7, label: 'Communication', value: 'COMMUNICATION', color: 'purple' },
        { position: 8, label: 'Other', value: 'OTHER', color: 'gray' },
      ],
    },
    {
      universalIdentifier: f('description'),
      type: FieldType.RICH_TEXT,
      name: 'description',
      label: 'Problem Detail',
      isNullable: true,
    },
    {
      universalIdentifier: f('evidence'),
      type: FieldType.TEXT,
      name: 'evidence',
      label: 'Evidence',
      isNullable: true,
    },
    {
      universalIdentifier: f('estimatedImpact'),
      type: FieldType.TEXT,
      name: 'estimatedImpact',
      label: 'Estimated Impact',
      isNullable: true,
    },
    {
      universalIdentifier: f('possibleSolution'),
      type: FieldType.RICH_TEXT,
      name: 'possibleSolution',
      label: 'Possible Solution',
      isNullable: true,
    },
    {
      universalIdentifier: f('automationOpportunity'),
      type: FieldType.BOOLEAN,
      name: 'automationOpportunity',
      label: 'Automation Opportunity',
      defaultValue: false,
    },
    {
      universalIdentifier: f('potentialAutomation'),
      type: FieldType.TEXT,
      name: 'potentialAutomation',
      label: 'Potential Automation',
      isNullable: true,
    },
    {
      universalIdentifier: f('discussedWithClient'),
      type: FieldType.BOOLEAN,
      name: 'discussedWithClient',
      label: 'Discussed With Client',
      defaultValue: false,
    },
    {
      universalIdentifier: f('status'),
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      defaultValue: "'OBSERVED'",
      options: [
        { position: 0, label: 'Observed', value: 'OBSERVED', color: 'gray' },
        { position: 1, label: 'Investigating', value: 'INVESTIGATING', color: 'blue' },
        { position: 2, label: 'Discussed', value: 'DISCUSSED', color: 'yellow' },
        { position: 3, label: 'Approved', value: 'APPROVED', color: 'green' },
        { position: 4, label: 'Solved', value: 'SOLVED', color: 'jade' },
        { position: 5, label: 'Not Worth Pursuing', value: 'NOT_WORTH_PURSUING', color: 'red' },
      ],
    },
    {
      universalIdentifier: f('resolvedAt'),
      type: FieldType.DATE,
      name: 'resolvedAt',
      label: 'Resolved On',
      isNullable: true,
    },
  ],
});